# Generated by Django 2.2.5 on 2019-09-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='era5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataname', models.CharField(max_length=200)),
                ('chartname', models.CharField(max_length=200)),
                ('intime', models.DateTimeField()),
            ],
        ),
    ]
