# Generated by Django 2.2.5 on 2019-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='era5',
            name='intime',
            field=models.CharField(max_length=200),
        ),
    ]
